package cc.smartcash.wallet.Models

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty

import java.io.Serializable

@JsonIgnoreProperties(ignoreUnknown = true)
class CurrentPrices : Serializable {
    // Getter Methods

    @JsonProperty("FJD")
    var fjd: Float = 0.toFloat()
    @JsonProperty("MXN")
    var mxn: Float = 0.toFloat()
    @JsonProperty("STD")
    var std: Float = 0.toFloat()
    @JsonProperty("SCR")
    var scr: Float = 0.toFloat()
    @JsonProperty("CDF")
    var cdf: Float = 0.toFloat()
    @JsonProperty("BBD")
    var bbd: Float = 0.toFloat()
    @JsonProperty("GTQ")
    var gtq: Float = 0.toFloat()
    @JsonProperty("CLP")
    var clp: Float = 0.toFloat()
    @JsonProperty("HNL")
    var hnl: Float = 0.toFloat()
    @JsonProperty("UGX")
    var ugx: Float = 0.toFloat()
    @JsonProperty("ZAR")
    var zar: Float = 0.toFloat()
    @JsonProperty("TND")
    var tnd: Float = 0.toFloat()
    @JsonProperty("STN")
    var stn: Float = 0.toFloat()
    @JsonProperty("CUC")
    var cuc: Float = 0.toFloat()
    @JsonProperty("BSD")
    var bsd: Float = 0.toFloat()
    @JsonProperty("SLL")
    var sll: Float = 0.toFloat()
    @JsonProperty("SDG")
    var sdg: Float = 0.toFloat()
    @JsonProperty("IQD")
    var iqd: Float = 0.toFloat()
    @JsonProperty("CUP")
    var cup: Float = 0.toFloat()
    @JsonProperty("GMD")
    var gmd: Float = 0.toFloat()
    @JsonProperty("TWD")
    var twd: Float = 0.toFloat()
    @JsonProperty("RSD")
    var rsd: Float = 0.toFloat()
    @JsonProperty("DOP")
    var dop: Float = 0.toFloat()
    @JsonProperty("KMF")
    var kmf: Float = 0.toFloat()
    @JsonProperty("MYR")
    var myr: Float = 0.toFloat()
    @JsonProperty("FKP")
    var fkp: Float = 0.toFloat()
    @JsonProperty("XOF")
    var xof: Float = 0.toFloat()
    @JsonProperty("GEL")
    var gel: Float = 0.toFloat()
    @JsonProperty("BTC")
    var btc: Float = 0.toFloat()
    @JsonProperty("UYU")
    var uyu: Float = 0.toFloat()
    @JsonProperty("MAD")
    var mad: Float = 0.toFloat()
    @JsonProperty("CVE")
    var cve: Float = 0.toFloat()
    @JsonProperty("TOP")
    var top: Float = 0.toFloat()
    @JsonProperty("AZN")
    var azn: Float = 0.toFloat()
    @JsonProperty("OMR")
    var omr: Float = 0.toFloat()
    @JsonProperty("PGK")
    var pgk: Float = 0.toFloat()
    @JsonProperty("KES")
    var kes: Float = 0.toFloat()
    @JsonProperty("SEK")
    var sek: Float = 0.toFloat()
    @JsonProperty("CNH")
    var cnh: Float = 0.toFloat()
    @JsonProperty("BTN")
    var btn: Float = 0.toFloat()
    @JsonProperty("UAH")
    var uah: Float = 0.toFloat()
    @JsonProperty("GNF")
    var gnf: Float = 0.toFloat()
    @JsonProperty("ERN")
    var ern: Float = 0.toFloat()
    @JsonProperty("MZN")
    var mzn: Float = 0.toFloat()
    @JsonProperty("SVC")
    var svc: Float = 0.toFloat()
    @JsonProperty("ARS")
    var ars: Float = 0.toFloat()
    @JsonProperty("QAR")
    var qar: Float = 0.toFloat()
    @JsonProperty("IRR")
    var irr: Float = 0.toFloat()
    @JsonProperty("MRO")
    var mro: Float = 0.toFloat()
    @JsonProperty("XPD")
    var xpd: Float = 0.toFloat()
    @JsonProperty("CNY")
    var cny: Float = 0.toFloat()
    @JsonProperty("THB")
    var thb: Float = 0.toFloat()
    @JsonProperty("UZS")
    var uzs: Float = 0.toFloat()
    @JsonProperty("XPF")
    var xpf: Float = 0.toFloat()
    @JsonProperty("MRU")
    var mru: Float = 0.toFloat()
    @JsonProperty("BDT")
    var bdt: Float = 0.toFloat()
    @JsonProperty("LYD")
    var lyd: Float = 0.toFloat()
    @JsonProperty("BMD")
    var bmd: Float = 0.toFloat()
    @JsonProperty("KWD")
    var kwd: Float = 0.toFloat()
    @JsonProperty("PHP")
    var php: Float = 0.toFloat()
    @JsonProperty("XPT")
    var xpt: Float = 0.toFloat()
    @JsonProperty("RUB")
    var rub: Float = 0.toFloat()
    @JsonProperty("PYG")
    var pyg: Float = 0.toFloat()
    @JsonProperty("ISK")
    var isk: Float = 0.toFloat()
    @JsonProperty("JMD")
    var jmd: Float = 0.toFloat()
    @JsonProperty("COP")
    var cop: Float = 0.toFloat()
    @JsonProperty("MKD")
    var mkd: Float = 0.toFloat()
    @JsonProperty("USD")
    var usd: Float = 0.toFloat()
    @JsonProperty("DZD")
    var dzd: Float = 0.toFloat()
    @JsonProperty("PAB")
    var pab: Float = 0.toFloat()
    @JsonProperty("GGP")
    var ggp: Float = 0.toFloat()
    @JsonProperty("SGD")
    var sgd: Float = 0.toFloat()
    @JsonProperty("ETB")
    var etb: Float = 0.toFloat()
    @JsonProperty("JEP")
    var jep: Float = 0.toFloat()
    @JsonProperty("KGS")
    var kgs: Float = 0.toFloat()
    @JsonProperty("SOS")
    var sos: Float = 0.toFloat()
    @JsonProperty("VEF")
    var vef: Float = 0.toFloat()
    @JsonProperty("VUV")
    var vuv: Float = 0.toFloat()
    @JsonProperty("LAK")
    var lak: Float = 0.toFloat()
    @JsonProperty("BND")
    var bnd: Float = 0.toFloat()
    @JsonProperty("XAF")
    var xaf: Float = 0.toFloat()
    @JsonProperty("LRD")
    var lrd: Float = 0.toFloat()
    @JsonProperty("XAG")
    var xag: Float = 0.toFloat()
    @JsonProperty("CHF")
    var chf: Float = 0.toFloat()
    @JsonProperty("HRK")
    var hrk: Float = 0.toFloat()
    // Setter Methods

    @JsonProperty("ALL")
    var all: Float = 0.toFloat()
    @JsonProperty("DJF")
    var djf: Float = 0.toFloat()
    @JsonProperty("VES")
    var ves: Float = 0.toFloat()
    @JsonProperty("ZMW")
    var zmw: Float = 0.toFloat()
    @JsonProperty("TZS")
    var tzs: Float = 0.toFloat()
    @JsonProperty("VND")
    var vnd: Float = 0.toFloat()
    @JsonProperty("XAU")
    var xau: Float = 0.toFloat()
    @JsonProperty("AUD")
    var aud: Float = 0.toFloat()
    @JsonProperty("ILS")
    var ils: Float = 0.toFloat()
    @JsonProperty("GHS")
    var ghs: Float = 0.toFloat()
    @JsonProperty("GYD")
    var gyd: Float = 0.toFloat()
    @JsonProperty("KPW")
    var kpw: Float = 0.toFloat()
    @JsonProperty("BOB")
    var bob: Float = 0.toFloat()
    @JsonProperty("KHR")
    var khr: Float = 0.toFloat()
    @JsonProperty("MDL")
    var mdl: Float = 0.toFloat()
    @JsonProperty("IDR")
    var idr: Float = 0.toFloat()
    @JsonProperty("KYD")
    var kyd: Float = 0.toFloat()
    @JsonProperty("AMD")
    var amd: Float = 0.toFloat()
    @JsonProperty("BWP")
    var bwp: Float = 0.toFloat()
    @JsonProperty("SHP")
    var shp: Float = 0.toFloat()
    @JsonProperty("TRY")
    var `try`: Float = 0.toFloat()
    @JsonProperty("LBP")
    var lbp: Float = 0.toFloat()
    @JsonProperty("TJS")
    var tjs: Float = 0.toFloat()
    @JsonProperty("JOD")
    var jod: Float = 0.toFloat()
    @JsonProperty("AED")
    var aed: Float = 0.toFloat()
    @JsonProperty("HKD")
    var hkd: Float = 0.toFloat()
    @JsonProperty("RWF")
    var rwf: Float = 0.toFloat()
    @JsonProperty("EUR")
    var eur: Float = 0.toFloat()
    @JsonProperty("LSL")
    var lsl: Float = 0.toFloat()
    @JsonProperty("DKK")
    var dkk: Float = 0.toFloat()
    @JsonProperty("CAD")
    var cad: Float = 0.toFloat()
    @JsonProperty("BGN")
    var bgn: Float = 0.toFloat()
    @JsonProperty("MMK")
    var mmk: Float = 0.toFloat()
    @JsonProperty("MUR")
    var mur: Float = 0.toFloat()
    @JsonProperty("NOK")
    var nok: Float = 0.toFloat()
    @JsonProperty("SYP")
    var syp: Float = 0.toFloat()
    @JsonProperty("IMP")
    var imp: Float = 0.toFloat()
    @JsonProperty("ZWL")
    var zwl: Float = 0.toFloat()
    @JsonProperty("GIP")
    var gip: Float = 0.toFloat()
    @JsonProperty("RON")
    var ron: Float = 0.toFloat()
    @JsonProperty("LKR")
    var lkr: Float = 0.toFloat()
    @JsonProperty("NGN")
    var ngn: Float = 0.toFloat()
    @JsonProperty("CRC")
    var crc: Float = 0.toFloat()
    @JsonProperty("CZK")
    var czk: Float = 0.toFloat()
    @JsonProperty("PKR")
    var pkr: Float = 0.toFloat()
    @JsonProperty("XCD")
    var xcd: Float = 0.toFloat()
    @JsonProperty("ANG")
    var ang: Float = 0.toFloat()
    @JsonProperty("HTG")
    var htg: Float = 0.toFloat()
    @JsonProperty("BHD")
    var bhd: Float = 0.toFloat()
    @JsonProperty("KZT")
    var kzt: Float = 0.toFloat()
    @JsonProperty("SRD")
    var srd: Float = 0.toFloat()
    @JsonProperty("SZL")
    var szl: Float = 0.toFloat()
    @JsonProperty("SAR")
    var sar: Float = 0.toFloat()
    @JsonProperty("TTD")
    var ttd: Float = 0.toFloat()
    @JsonProperty("YER")
    var yer: Float = 0.toFloat()
    @JsonProperty("MVR")
    var mvr: Float = 0.toFloat()
    @JsonProperty("AFN")
    var afn: Float = 0.toFloat()
    @JsonProperty("INR")
    var inr: Float = 0.toFloat()
    @JsonProperty("AWG")
    var awg: Float = 0.toFloat()
    @JsonProperty("KRW")
    var krw: Float = 0.toFloat()
    @JsonProperty("NPR")
    var npr: Float = 0.toFloat()
    @JsonProperty("JPY")
    var jpy: Float = 0.toFloat()
    @JsonProperty("MNT")
    var mnt: Float = 0.toFloat()
    @JsonProperty("AOA")
    var aoa: Float = 0.toFloat()
    @JsonProperty("PLN")
    var pln: Float = 0.toFloat()
    @JsonProperty("GBP")
    var gbp: Float = 0.toFloat()
    @JsonProperty("SBD")
    var sbd: Float = 0.toFloat()
    @JsonProperty("BYN")
    var byn: Float = 0.toFloat()
    @JsonProperty("HUF")
    var huf: Float = 0.toFloat()
    @JsonProperty("BIF")
    var bif: Float = 0.toFloat()
    @JsonProperty("MWK")
    var mwk: Float = 0.toFloat()
    @JsonProperty("MGA")
    var mga: Float = 0.toFloat()
    @JsonProperty("XDR")
    var xdr: Float = 0.toFloat()
    @JsonProperty("BZD")
    var bzd: Float = 0.toFloat()
    @JsonProperty("BAM")
    var bam: Float = 0.toFloat()
    @JsonProperty("EGP")
    var egp: Float = 0.toFloat()
    @JsonProperty("MOP")
    var mop: Float = 0.toFloat()
    @JsonProperty("NAD")
    var nad: Float = 0.toFloat()
    @JsonProperty("SSP")
    var ssp: Float = 0.toFloat()
    @JsonProperty("NIO")
    var nio: Float = 0.toFloat()
    @JsonProperty("PEN")
    var pen: Float = 0.toFloat()
    @JsonProperty("NZD")
    var nzd: Float = 0.toFloat()
    @JsonProperty("WST")
    var wst: Float = 0.toFloat()
    @JsonProperty("TMT")
    var tmt: Float = 0.toFloat()
    @JsonProperty("CLF")
    var clf: Float = 0.toFloat()
    @JsonProperty("BRL")
    var brl: Float = 0.toFloat()
}
